/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a48707eb879e60f4a9cffc8d5df3c903)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	WEB_SEARCH_TOOL: Service /* entrypoint WebSearchTool from web-search-tool */;
	ANALYTICS_TOOL: Service /* entrypoint AnalyticsTool from analytics-tool */;
	DB_CLIENT_TOOL: Service /* entrypoint DbClientTool from db-client-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
