/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6668b63c27301d0be906bc46288834c4)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	TEST_RUNNER_TOOL: Service /* entrypoint TestRunnerTool from test-runner-tool */;
	CI_STATUS_TOOL: Service /* entrypoint CiStatusTool from ci-status-tool */;
	COVERAGE_TOOL: Service /* entrypoint CoverageTool from coverage-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
