packages:
  - "packages/*"
  - "packages/flax/packages/*"
  - "packages/flax/packages/agents/*"
  - "packages/flax/packages/tools/*"
allowBuilds:
  "@google/genai": false
  "@mongodb-js/zstd": false
  core-js-pure: false
  esbuild: true
  node-liblzma: false
  protobufjs: false
  workerd: true
