/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 49c9563ba5e951a0497545f6e7531c86)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	JIRA_LINEAR_TOOL: Service /* entrypoint JiraLinearTool from jira-linear-tool */;
	SUPPORT_TICKETS_TOOL: Service /* entrypoint SupportTicketsTool from support-tickets-tool */;
	SENTIMENT_ANALYSIS_TOOL: Service /* entrypoint SentimentAnalysisTool from sentiment-analysis-tool */;
	WEB_SEARCH_TOOL: Service /* entrypoint WebSearchTool from web-search-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
