/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: df10c6c35298aee5bcaf0b6d8baafc00)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	DOCS_GENERATOR_TOOL: Service /* entrypoint DocsGeneratorTool from docs-generator-tool */;
	CONFLUENCE_NOTION_TOOL: Service /* entrypoint ConfluenceNotionTool from confluence-notion-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
