/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 71280fb0dfb0d13b9750b2cfa2299ffd)
interface __BaseEnv_Env {
  FLAX_DB: D1Database;
  AI: Ai;
  FEATURE_FLAGS_TOOL: Service /* entrypoint FeatureFlagsTool from feature-flags-tool */;
  GITHUB_TOOL: Service /* entrypoint GithubTool from github-tool */;
  CHANGELOG_TOOL: Service /* entrypoint ChangelogTool from changelog-tool */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
