/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3a9bb818a5d1f8a9b00d12d9692b5a25)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	DIAGRAMMING_TOOL: Service /* entrypoint DiagrammingTool from diagramming-tool */;
	CLOUD_PRICING_TOOL: Service /* entrypoint CloudPricingTool from cloud-pricing-tool */;
	IAC_TOOL: Service /* entrypoint IacTool from iac-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
