/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 327e30c262ed0c616493be3ee1399aa4)
interface __BaseEnv_Env {
  FLAX_DB: D1Database;
  AI: Ai;
  DB_CLIENT_TOOL: Service /* entrypoint DbClientTool from db-client-tool */;
  MIGRATIONS_TOOL: Service /* entrypoint MigrationsTool from migrations-tool */;
  QUERY_PROFILER_TOOL: Service /* entrypoint QueryProfilerTool from query-profiler-tool */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
