/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 39798c98266d6ee252bea7b08440a154)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	JIRA_LINEAR_TOOL: Service /* entrypoint JiraLinearTool from jira-linear-tool */;
	CONFLUENCE_NOTION_TOOL: Service /* entrypoint ConfluenceNotionTool from confluence-notion-tool */;
	TRANSCRIPTION_TOOL: Service /* entrypoint TranscriptionTool from transcription-tool */;
	VECTOR_STORE_TOOL: Service /* entrypoint VectorStoreTool from vector-store-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
