/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ba892dd4d7626792e2e53f5874b0394e)
interface __BaseEnv_Env {
  FLAX_DB: D1Database;
  AI: Ai;
  FIGMA_TOOL: Service /* entrypoint FigmaTool from figma-tool */;
  IMAGE_GEN_TOOL: Service /* entrypoint ImageGenTool from image-gen-tool */;
  ACCESSIBILITY_CHECKER_TOOL: Service /* entrypoint AccessibilityCheckerTool from accessibility-checker-tool */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
