/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d2240a1ef833e676bb6ef0477b5cd0b6)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	GITHUB_TOOL: Service /* entrypoint GithubTool from github-tool */;
	STATIC_ANALYSIS_TOOL: Service /* entrypoint StaticAnalysisTool from static-analysis-tool */;
	CI_STATUS_TOOL: Service /* entrypoint CiStatusTool from ci-status-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
