/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 57e29d796d1f170e580b442e5b180883)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	SECURITY_SCAN_TOOL: Service /* entrypoint SecurityScanTool from security-scan-tool */;
	SBOM_TOOL: Service /* entrypoint SbomTool from sbom-tool */;
	PENTEST_TOOL: Service /* entrypoint PentestTool from pentest-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
