/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d423aefc28f1b75123fe59a8e08fb3c2)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	CICD_PIPELINE_TOOL: Service /* entrypoint CicdPipelineTool from cicd-pipeline-tool */;
	CONTAINERS_TOOL: Service /* entrypoint ContainersTool from containers-tool */;
	IAC_TOOL: Service /* entrypoint IacTool from iac-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
