/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 480d366f93c4b934fd5123ecccfe3aab)
interface __BaseEnv_Env {
  FLAX_DB: D1Database;
  AI: Ai;
  GITHUB_TOOL: Service /* entrypoint GithubTool from github-tool */;
  PACKAGE_MANAGER_TOOL: Service /* entrypoint PackageManagerTool from package-manager-tool */;
  LINT_LANGSERVER_TOOL: Service /* entrypoint LintLangserverTool from lint-langserver-tool */;
  SANDBOX_EXEC_TOOL: Service /* entrypoint SandboxExecTool from sandbox-exec-tool */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
