/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 72ef3500571bdc0eedb681da773f47b1)
interface __BaseEnv_Env {
	FLAX_DB: D1Database;
	AI: Ai;
	SUPPORT_TICKETS_TOOL: Service /* entrypoint SupportTicketsTool from support-tickets-tool */;
	SENTIMENT_ANALYSIS_TOOL: Service /* entrypoint SentimentAnalysisTool from sentiment-analysis-tool */;
	JIRA_LINEAR_TOOL: Service /* entrypoint JiraLinearTool from jira-linear-tool */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
