/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bb21bef7c04309168376a26e2fef9447)
interface __BaseEnv_Env {
  FLAX_DB: D1Database;
  AI: Ai;
  TASK_QUEUE_TOOL: Service /* entrypoint TaskQueueTool from task-queue-tool */;
  JIRA_LINEAR_TOOL: Service /* entrypoint JiraLinearTool from jira-linear-tool */;
  PRODUCT_REQUIREMENTS_AGENT: Service /* entrypoint default from product-requirements-agent */;
  BUSINESS_DATA_ANALYST_AGENT: Service /* entrypoint default from business-data-analyst-agent */;
  SOLUTIONS_ARCHITECT_AGENT: Service /* entrypoint default from solutions-architect-agent */;
  UX_UI_DESIGNER_AGENT: Service /* entrypoint default from ux-ui-designer-agent */;
  CODING_AGENT: Service /* entrypoint default from coding-agent */;
  DATABASE_DATA_ENGINEER_AGENT: Service /* entrypoint default from database-data-engineer-agent */;
  CODE_REVIEW_AGENT: Service /* entrypoint default from code-review-agent */;
  QA_TEST_AGENT: Service /* entrypoint default from qa-test-agent */;
  SECURITY_APPSEC_AGENT: Service /* entrypoint default from security-appsec-agent */;
  DEVOPS_CICD_AGENT: Service /* entrypoint default from devops-cicd-agent */;
  RELEASE_MANAGER_AGENT: Service /* entrypoint default from release-manager-agent */;
  SRE_OBSERVABILITY_AGENT: Service /* entrypoint default from sre-observability-agent */;
  DOCUMENTATION_AGENT: Service /* entrypoint default from documentation-agent */;
  SUPPORT_FEEDBACK_AGENT: Service /* entrypoint default from support-feedback-agent */;
  SUPPORT_AGENT: Service /* entrypoint default from support-agent */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
