export const DRIZZLE_HEADER = `// Generated by nomo/migrations reflect

import { sqliteTable, text, integer, real, blob, foreignKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
`;

export const ZOD_HEADER = `import { createSelectSchema, createInsertSchema } from 'drizzle-zod';
import * as schema from './schema';
`;

export const ZOD_HEADER_INDIVIDUAL = `import { createSelectSchema, createInsertSchema } from 'drizzle-zod';
import * as schema from '../../db/schema/schema';
`;

export const TABLE_START = `
export const {{tableName}} = sqliteTable('{{tableName}}', {
`;



export const MODEL_TEMPLATE = `// model
import { BaseModel, type DatabaseInstance } from 'nomo/models';
import { {{tableName}} } from '../db/schema/schema';
import type { {{typeName}}, New{{typeName}} } from './types';

export class {{modelName}} extends BaseModel<typeof {{tableName}}, {{typeName}}, New{{typeName}}> {
  constructor(db: DatabaseInstance) {
    super(db, {{tableName}});
{{relationships}}  }
}
`;

export const COLUMN_START = `  {{name}}: {{type}}`;
export const COLUMN_PK = `.primaryKey()`;
export const COLUMN_AUTO_INCREMENT = `.primaryKey({ autoIncrement: true })`;
export const COLUMN_NOT_NULL = `.notNull()`;
export const COLUMN_DEFAULT = `.default({{value}})`;
export const COLUMN_LINE_END = `,
`;

export const TABLE_COLUMN_END = `  }`;
export const TABLE_EXTRA_START = `, (table) => [
`;
export const REFERENCE = `  foreignKey({
    columns: [table.{{column}}],
    foreignColumns: [{{foreignTable}}.{{foreignColumn}}],
  }).onDelete('{{onDelete}}'),
`;
export const INDEX = `  index('{{name}}').on({{columns}}),
`;
export const UNIQUE_INDEX = `  uniqueIndex('{{name}}').on({{columns}}),
`;
export const TABLE_EXTRA_END = `]`;
export const TABLE_END = `);
`;

export const ZOD_TEMPLATE = `
// --- {{typeName}} ---
export const {{tableName}}SelectSchema = createSelectSchema(schema.{{tableName}});
export const {{tableName}}InsertSchema = createInsertSchema(schema.{{tableName}});
export const {{tableName}}UpdateSchema = {{tableName}}InsertSchema.partial();

/** Base Types */
export type {{typeName}} = typeof schema.{{tableName}}.$inferSelect;
export type New{{typeName}} = typeof schema.{{tableName}}.$inferInsert;
export type Update{{typeName}}Payload = Partial<New{{typeName}}>;
export type Patch{{typeName}}Payload = Update{{typeName}}Payload;

/** Operation Payloads */
export type CreateMany{{typeName}}Payload = New{{typeName}}[];
export type {{typeName}}Filter = Partial<{{typeName}}>;
export type {{typeName}}Where = {{typeName}}Filter;

/** Key-Value Pattern Types */
export type {{typeName}}Key = keyof {{typeName}};
export type {{typeName}}KeyValue<K extends {{typeName}}Key = {{typeName}}Key> = {
	key: K;
	value: {{typeName}}[K];
};

export type Get{{typeName}}ByKeyAndValue = {{typeName}}KeyValue;
export type Update{{typeName}}ByKeyAndValue = {{typeName}}KeyValue & { data: Update{{typeName}}Payload };
export type Patch{{typeName}}ByKeyAndValue = Update{{typeName}}ByKeyAndValue;
export type Delete{{typeName}}ByKeyAndValue = {{typeName}}KeyValue;
export type Exists{{typeName}}ByKeyAndValue = {{typeName}}KeyValue;
export type Count{{typeName}}ByKeyAndValue = {{typeName}}KeyValue;
export type Upsert{{typeName}}ByKeyAndValue = {{typeName}}KeyValue & { data: New{{typeName}} };
`;
export const BUNDLE_HEADER = `// Generated by nomo/migrations bundle

export const migrations = [
`;

export const BUNDLE_ITEM = `  {
    name: '{{name}}'{{durableObjectClass}},
    sql: \`{{sql}}\`,
  },
`;

export const BUNDLE_FOOTER = `];
`;

export const RELATIONSHIP_TEMPLATE = `    this.{{type}}('{{name}}', { model: '{{targetModel}}'{{options}} });
`;
