/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 082732cf0777da32e56f6c58cd5957d9)
interface __BaseEnv_Env {
  FLAX_DB: D1Database;
  AI: Ai;
  MONITORING_TOOL: Service /* entrypoint MonitoringTool from monitoring-tool */;
  PAGERDUTY_TOOL: Service /* entrypoint PagerdutyTool from pagerduty-tool */;
  LOG_AGGREGATION_TOOL: Service /* entrypoint LogAggregationTool from log-aggregation-tool */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
